#spring.application.name=bff
#
#core.authentication.service.url=https://localhost:Authservice
#core.main.service.url=https://localhost:Mainservice
#core.my.service.url=https://localhost:BFF
#
## JWT RSA Key
#jwt.rsa-public-key=classpath:certs/PublicKey.pem
#
#server.port=8089
#
##logger.type
#logging.framework=slf4j
#
#spring.web.resources.static-locations=classpath:/static/
